const fs = require('fs');
const path = 'c:\\Users\\ksuib\\Desktop\\Ibrahim AL-duaydi\\My own program\\pro-pricing-platform\\constants.ts';

let content = fs.readFileSync(path, 'utf8');

const newDb = `export const ITEMS_DATABASE: BaseItem[] = [
    // ================= 00. معلومات وتكاليف إدارية =================
    { id: "00.01", category: "gov_fees", type: "all", name: { ar: "إصدار رخصة بناء (رسوم بلدية)", en: "Building Permit", fr: "Permis de Construire", zh: "建筑许可证" }, unit: "م2", qty: 450, baseMaterial: 4, baseLabor: 0, waste: 0, suppliers: [{ id: 'balady', name: { ar: 'بلدي', en: 'Balady', fr: 'Balady', zh: 'Balady' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC-Admin", soilFactor: false, dependency: 'build_area', excludeProfit: true },
    { id: "00.02", category: "gov_fees", type: "all", name: { ar: "تأمين ملاذ (عيوب خفية)", en: "Latent Defects Insurance", fr: "Assurance Vices Cachés", zh: "潜在缺陷保险" }, unit: "بوليصة", qty: 1, baseMaterial: 12000, baseLabor: 0, waste: 0, suppliers: [{ id: 'malath', name: { ar: 'ملاذ', en: 'Malath', fr: 'Malath', zh: 'Malath' }, tier: 'standard', priceMultiplier: 1 }], sbc: "LIDI-Reg", soilFactor: false, dependency: 'build_area', excludeProfit: true },
    { id: "00.03", category: "gov_fees", type: "all", name: { ar: "إشراف هندسي معتمد", en: "Engineering Supervision", fr: "Supervision", zh: "工程监理" }, unit: "زيارة", qty: 12, baseMaterial: 0, baseLabor: 400, waste: 0, suppliers: [{ id: 'eng_off', name: { ar: 'مكتب هندسي', en: 'Eng Office', fr: 'Bureau d\\'Ing', zh: '工程办公室' }, tier: 'standard', priceMultiplier: 1 }], sbc: "Eng-Sup", soilFactor: false, dependency: 'fixed', excludeProfit: true },

    // ================= 01. أعمال الحفر (Excavation) =================
    { id: "01.01", category: "site", type: "all", name: { ar: "تنظيف الموقع وقشط السطح", en: "Site Clearance & Topsoil Stripping", fr: "Nettoyage du Site", zh: "场地清理" }, unit: "م2", qty: 600, baseMaterial: 0, baseLabor: 5, waste: 0, suppliers: [{ id: 'exc_1', name: { ar: 'معدات ثقيلة', en: 'Heavy Equip', fr: 'Équip Lourd', zh: '重型设备' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-1", soilFactor: false, dependency: 'land_area', defaultParams: { topsoilStrippingDepth: 0.2 } },
    { id: "01.02", category: "site", type: "all", name: { ar: "حفر ميكانيكي (تربة عادية)", en: "Mechanical Excavation (Normal Soil)", fr: "Excavation Mécanique", zh: "机械挖掘" }, unit: "م3", qty: 600, baseMaterial: 0, baseLabor: 15, waste: 0, suppliers: [{ id: 'exc_1', name: { ar: 'معدات ثقيلة', en: 'Heavy Equip', fr: 'Équip Lourd', zh: '重型设备' }, tier: 'standard', priceMultiplier: 1 }, { id: 'exc_2', name: { ar: 'مقاولين حفر', en: 'Excavation Cont.', fr: 'Entrepreneurs Exc.', zh: '挖掘承包商' }, tier: 'budget', priceMultiplier: 0.85 }], sbc: "SBC 303-2", soilFactor: true, dependency: 'land_area', defaultParams: { excavationDepth: 2.5 } },
    { id: "01.03", category: "site", type: "all", name: { ar: "حفر صخري (نقار/تفجير)", en: "Rock Excavation", fr: "Excavation Rocheuse", zh: "岩石挖掘" }, unit: "م3", qty: 0, baseMaterial: 0, baseLabor: 45, waste: 0, suppliers: [{ id: 'exc_1', name: { ar: 'معدات ثقيلة', en: 'Heavy Equip', fr: 'Équip Lourd', zh: '重型设备' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-3", soilFactor: true, dependency: 'land_area', defaultParams: { excavationDepth: 2.5 } },
    { id: "01.04", category: "site", type: "all", name: { ar: "سند جوانب الحفر (Shoring)", en: "Excavation Shoring", fr: "Étayage d\\'Excavation", zh: "挖掘支撑" }, unit: "م2", qty: 0, baseMaterial: 150, baseLabor: 80, waste: 0, suppliers: [{ id: 'shore_1', name: { ar: 'مقاول سند', en: 'Shoring Cont.', fr: 'Étayage Cont.', zh: '支撑承包商' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-4", soilFactor: false, dependency: 'land_area', defaultParams: { shoringType: 'none', shoringDepth: 2.5 } },
    { id: "01.05", category: "site", type: "all", name: { ar: "نزح المياه الجوفية (Dewatering)", en: "Dewatering", fr: "Épuisement des Eaux", zh: "排水" }, unit: "مقطوعية", qty: 0, baseMaterial: 5000, baseLabor: 3000, waste: 0, suppliers: [{ id: 'pump_1', name: { ar: 'نظام ضخ', en: 'Pumping Sys.', fr: 'Syst. Pompage', zh: '泵送系统' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-5", soilFactor: false, dependency: 'fixed', defaultParams: { dewateringType: 'none', waterTableDepth: 1.5 } },
    { id: "01.06", category: "site", type: "all", name: { ar: "ترحيل ناتج الحفر (للمقالب)", en: "Debris Removal", fr: "Évacuation des Débris", zh: "渣土清运" }, unit: "م3", qty: 600, baseMaterial: 0, baseLabor: 12, waste: 0, suppliers: [{ id: 'trans_1', name: { ar: 'نقليات', en: 'Transport Co.', fr: 'Transport', zh: '运输公司' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 302-Rem", soilFactor: false, dependency: 'land_area' },

    // ================= 02. أعمال الردم والإحلال (Backfill & Compaction) =================
    { id: "02.01", category: "site", type: "all", name: { ar: "إحلال تربة (ردم هندسي)", en: "Soil Replacement (Backfill)", fr: "Remplacement du Sol", zh: "回填" }, unit: "م3", qty: 450, baseMaterial: 22, baseLabor: 10, waste: 0.10, suppliers: [{ id: 'soil_1', name: { ar: 'نقليات الرمال', en: 'Sand Trans', fr: 'Trans Sable', zh: '沙运' }, tier: 'standard', priceMultiplier: 1 }, { id: 'soil_2', name: { ar: 'رمال الخرج', en: 'Al-Kharj Sand', fr: 'Sable Al-Kharj', zh: 'Al-Kharj沙' }, tier: 'premium', priceMultiplier: 1.15 }], sbc: "SBC 303-Fill", soilFactor: false, dependency: 'land_area', defaultParams: { backfillDensity: 1800, subsidenceRatio: 0.10 } },
    { id: "02.02", category: "site", type: "all", name: { ar: "ردم بتربة الموقع", en: "Backfill (Site Soil)", fr: "Remblai (Sol du Site)", zh: "场地土回填" }, unit: "م3", qty: 0, baseMaterial: 0, baseLabor: 8, waste: 0, suppliers: [{ id: 'exc_1', name: { ar: 'معدات ثقيلة', en: 'Heavy Equip', fr: 'Équip Lourd', zh: '重型设备' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-SiteFill", soilFactor: false, dependency: 'land_area' },
    { id: "02.03", category: "site", type: "all", name: { ar: "ردم مستورد (صبّيز)", en: "Imported Fill", fr: "Remblai d\\'Apport", zh: "进口回填土" }, unit: "م3", qty: 0, baseMaterial: 25, baseLabor: 12, waste: 0.05, suppliers: [{ id: 'soil_1', name: { ar: 'نقليات الرمال', en: 'Sand Trans', fr: 'Trans Sable', zh: '沙运' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-ImpFill", soilFactor: false, dependency: 'land_area' },
    { id: "02.04", category: "site", type: "all", name: { ar: "دمك التربة (على طبقات)", en: "Soil Compaction (Layers)", fr: "Compactage du Sol", zh: "土壤压实" }, unit: "م2", qty: 300, baseMaterial: 0, baseLabor: 8, waste: 0, suppliers: [{ id: 'exc_1', name: { ar: 'معدات ثقيلة', en: 'Heavy Equip', fr: 'Équip Lourd', zh: '重型设备' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-Cmp", soilFactor: true, dependency: 'land_area', defaultParams: { compactionLayers: 3 } },
    { id: "02.05", category: "site", type: "all", name: { ar: "رش مبيد حشري (نمل أبيض)", en: "Anti-Termite Treatment", fr: "Traitement Anti-Termites", zh: "防白蚁处理" }, unit: "م2", qty: 300, baseMaterial: 8, baseLabor: 3, waste: 0, suppliers: [{ id: 'pest_1', name: { ar: 'مكافحة الحشرات', en: 'Pest Control', fr: 'Lutte Antiparasitaire', zh: '害虫防治' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-Pest", soilFactor: false, dependency: 'land_area' },
    { id: "02.06", category: "site", type: "all", name: { ar: "فرش نايلون (بولي إيثيلين)", en: "Polyethylene Sheets", fr: "Feuilles Polyéthylène", zh: "聚乙烯板" }, unit: "م2", qty: 300, baseMaterial: 4, baseLabor: 2, waste: 0.1, suppliers: [{ id: 'poly_1', name: { ar: 'مواد بناء', en: 'Building Mat', fr: 'Mat Construction', zh: '建筑材料' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 303-Poly", soilFactor: false, dependency: 'land_area' },

    // ================= 03. أعمال التأسيس (Foundation) =================
    { id: "03.01", category: "structure", type: "all", name: { ar: "خرسانة نظافة C20", en: "Plain Concrete C20", fr: "Béton C20", zh: "素混凝土 C20" }, unit: "م3", qty: 35, baseMaterial: 200, baseLabor: 90, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 304", soilFactor: false, dependency: 'land_area', defaultParams: { thickness: 10 } },
    { id: "03.02", category: "structure", type: "all", name: { ar: "خرسانة قواعد C35", en: "Reinforced Concrete Footings C35", fr: "Béton Armé Semelles C35", zh: "钢筋混凝土地基 C35" }, unit: "م3", qty: 90, baseMaterial: 260, baseLabor: 120, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-4", soilFactor: false, dependency: 'build_area', defaultParams: { cementContent: 7 } },
    { id: "03.03", category: "structure", type: "all", name: { ar: "خرسانة ميد أرضية C35", en: "Reinforced Concrete Tie Beams C35", fr: "Longrines Béton Armé C35", zh: "钢筋混凝土系梁 C35" }, unit: "م3", qty: 30, baseMaterial: 260, baseLabor: 120, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-TB", soilFactor: false, dependency: 'build_area' },
    { id: "03.04", category: "structure", type: "all", name: { ar: "خرسانة رقاب أعمدة C40", en: "Neck Columns Concrete C40", fr: "Béton Fûts C40", zh: "颈柱混凝土 C40" }, unit: "م3", qty: 15, baseMaterial: 280, baseLabor: 150, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-NC", soilFactor: false, dependency: 'build_area' },
    { id: "03.05", category: "structure", type: "all", name: { ar: "حديد تسليح أساسات (G60)", en: "Foundation Reinforcement Steel", fr: "Acier d\\'Armature Fondations", zh: "地基钢筋" }, unit: "طن", qty: 15, baseMaterial: 2750, baseLabor: 450, waste: 0.03, suppliers: suppliersSteel, sbc: "SBC 304-5", soilFactor: false, dependency: 'build_area' },
    { id: "03.06", category: "structure", type: "all", name: { ar: "شدات خشبية للأساسات", en: "Foundation Formwork", fr: "Coffrage Fondations", zh: "地基模板" }, unit: "م2", qty: 250, baseMaterial: 35, baseLabor: 45, waste: 0.15, suppliers: [{ id: 'form_1', name: { ar: 'شدات خشبية', en: 'Timber Forms', fr: 'Coffrages Bois', zh: '木质模板' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 304-Frm", soilFactor: false, dependency: 'build_area' },

    // ================= 04. تأسيس البدروم والدور الأرضي (Basement & Ground Floor) =================
    { id: "04.01", category: "structure", type: "all", name: { ar: "أعمدة البدروم/الأرضي C40", en: "Basement/Ground Columns C40", fr: "Colonnes Sous-sol/RDC C40", zh: "地下室/一楼柱 C40" }, unit: "م3", qty: 25, baseMaterial: 280, baseLabor: 150, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-Col", soilFactor: false, dependency: 'build_area' },
    { id: "04.02", category: "structure", type: "all", name: { ar: "الجدران الاستنادية (بدروم)", en: "Retaining Walls", fr: "Murs de Soutènement", zh: "挡土墙" }, unit: "م3", qty: 20, baseMaterial: 280, baseLabor: 150, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 304-Ret", soilFactor: true, dependency: 'land_area' },
    { id: "04.03", category: "structure", type: "all", name: { ar: "خرسانة سقف الدور الأرضي", en: "Ground Floor Slab Concrete", fr: "Béton Dalle RDC", zh: "一楼楼板混凝土" }, unit: "م3", qty: 45, baseMaterial: 270, baseLabor: 130, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-Slb1", soilFactor: false, dependency: 'build_area' },
    { id: "04.04", category: "structure", type: "all", name: { ar: "سلالم خرسانية", en: "Concrete Stairs", fr: "Escaliers Béton", zh: "混凝土楼梯" }, unit: "م3", qty: 8, baseMaterial: 290, baseLabor: 180, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 304-Strs", soilFactor: false, dependency: 'fixed' },

    // ================= 05. الهيكل الإنشائي (Superstructure - أدوار متكررة) =================
    { id: "05.01", category: "structure", type: "all", name: { ar: "أعمدة وجدران قص (متكررة)", en: "Upper Columns/Walls Concrete C40", fr: "Béton Colonnes Sup C40", zh: "上层柱墙混凝土 C40" }, unit: "م3", qty: 40, baseMaterial: 280, baseLabor: 150, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-ColUp", soilFactor: false, dependency: 'build_area' },
    { id: "05.02", category: "structure", type: "all", name: { ar: "خرسانة أسقف متكررة", en: "Upper Slabs Concrete", fr: "Béton Dalles Sup", zh: "上层楼板混凝土" }, unit: "م3", qty: 45, baseMaterial: 270, baseLabor: 130, waste: 0.03, suppliers: suppliersConcrete, sbc: "SBC 304-SlbUp", soilFactor: false, dependency: 'build_area' },
    { id: "05.03", category: "structure", type: "all", name: { ar: "حديد تسليح الهيكل العلوي", en: "Superstructure Reinforcement Steel", fr: "Acier d\\'Armature Sup", zh: "上部结构钢筋" }, unit: "طن", qty: 30, baseMaterial: 2750, baseLabor: 450, waste: 0.03, suppliers: suppliersSteel, sbc: "SBC 304-5UP", soilFactor: false, dependency: 'build_area' },
    { id: "05.04", category: "structure", type: "all", name: { ar: "بلك خارجي معزول (20سم)", en: "Ext. Insulated Blocks (20cm)", fr: "Blocs Isolés Ext.", zh: "外墙绝缘砌块" }, unit: "م2", qty: 400, baseMaterial: 55, baseLabor: 25, waste: 0.05, suppliers: [{ id: 'block_s', name: { ar: 'السعودية للطوب', en: 'Saudi Bricks', fr: 'Briques Saoudiennes', zh: '沙特砖' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 304-Blk", soilFactor: false, dependency: 'build_area' },
    { id: "05.05", category: "structure", type: "all", name: { ar: "بلك داخلي اسمنتي (15سم)", en: "Int. Cement Blocks (15cm)", fr: "Blocs Ciment Int.", zh: "内墙水泥砌块" }, unit: "م2", qty: 600, baseMaterial: 35, baseLabor: 22, waste: 0.05, suppliers: [{ id: 'block_c', name: { ar: 'مصانع محلية', en: 'Local Block', fr: 'Bloc Local', zh: '当地砌块' }, tier: 'budget', priceMultiplier: 0.9 }], sbc: "SBC 304-Blk-In", soilFactor: false, dependency: 'build_area' },
    { id: "05.06", category: "structure", type: "all", name: { ar: "بلاطة هوردي (بلك)", en: "Hordi Blocks", fr: "Blocs Hordi", zh: "空心砖" }, unit: "م2", qty: 280, baseMaterial: 25, baseLabor: 15, waste: 0.08, suppliers: [{ id: 'block_h', name: { ar: 'بلك هوردي', en: 'Hordi Block', fr: 'Bloc Hordi', zh: '空心砖' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 304-Hrd", soilFactor: false, dependency: 'build_area' },
    { id: "05.07", category: "structure", type: "all", name: { ar: "أعتاب خرسانية", en: "Concrete Lintels", fr: "Linteaux Béton", zh: "混凝土过梁" }, unit: "م.ط", qty: 100, baseMaterial: 25, baseLabor: 15, waste: 0.02, suppliers: suppliersConcrete, sbc: "SBC 304-Lin", soilFactor: false, dependency: 'build_area' },

    // ================= 06. أعمال العزل (Insulation) =================
    { id: "06.01", category: "insulation", type: "all", name: { ar: "عزل قواعد وميدات (بيتومين)", en: "Foundation Waterproofing", fr: "Étanchéité Fondations", zh: "地基防水" }, unit: "م2", qty: 400, baseMaterial: 18, baseLabor: 12, waste: 0.1, suppliers: [{ id: 'ins_bit', name: { ar: 'بيتومات', en: 'Bitumat', fr: 'Bitumat', zh: 'Bitumat' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 1101", soilFactor: false, dependency: 'land_area' },
    { id: "06.02", category: "insulation", type: "all", name: { ar: "خرسانة ميول الأسطح (Screed)", en: "Roof Screed", fr: "Chape Toit", zh: "屋顶找平层" }, unit: "م2", qty: 300, baseMaterial: 25, baseLabor: 15, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 1103", soilFactor: false, dependency: 'build_area' },
    { id: "06.03", category: "insulation", type: "all", name: { ar: "عزل مائي وحراري للأسطح (فوم)", en: "Roof Thermal/Water Insulation", fr: "Isolation Thermique/Eau Toit", zh: "屋顶防水隔热" }, unit: "م2", qty: 300, baseMaterial: 45, baseLabor: 20, waste: 0.05, suppliers: [{ id: 'ins_foam', name: { ar: 'عزل حراري', en: 'Thermal Ins', fr: 'Isol Thermique', zh: '隔热' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 1102", soilFactor: false, dependency: 'build_area' },
    { id: "06.04", category: "insulation", type: "all", name: { ar: "عزل مائي للحمامات والمطابخ", en: "Wet Areas Waterproofing", fr: "Étanchéité Salles d\\'Eau", zh: "湿区防水" }, unit: "م2", qty: 40, baseMaterial: 35, baseLabor: 25, waste: 0.1, suppliers: [{ id: 'ins_bit', name: { ar: 'بيتومات', en: 'Bitumat', fr: 'Bitumat', zh: 'Bitumat' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 1101-WC", soilFactor: false, dependency: 'rooms_area' },
    { id: "06.05", category: "insulation", type: "all", name: { ar: "عزل خزانات مياه أرضية", en: "Underground Tank Waterproofing", fr: "Étanchéité Réservoirs Souterrains", zh: "地下水箱防水" }, unit: "م2", qty: 30, baseMaterial: 45, baseLabor: 35, waste: 0.1, suppliers: [{ id: 'ins_bit', name: { ar: 'بيتومات', en: 'Bitumat', fr: 'Bitumat', zh: 'Bitumat' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 1101-Tnk", soilFactor: false, dependency: 'fixed' },

    // ================= 07. أعمال اللياسة (Plastering) =================
    { id: "07.01", category: "architecture", type: "all", name: { ar: "لياسة داخلية (أسمنتية)", en: "Internal Plaster", fr: "Enduit Intérieur", zh: "内墙抹灰" }, unit: "م2", qty: 2500, baseMaterial: 14, baseLabor: 20, waste: 0.08, suppliers: [{ id: 'plast', name: { ar: 'اسمنت اليمامة', en: 'Yamama Cement', fr: 'Ciment Yamama', zh: 'Yamama 水泥' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-Pl", soilFactor: false, dependency: 'rooms_area' },
    { id: "07.02", category: "architecture", type: "all", name: { ar: "لياسة خارجية (واجهات وأسوار)", en: "External Plaster", fr: "Enduit Extérieur", zh: "外墙抹灰" }, unit: "م2", qty: 400, baseMaterial: 18, baseLabor: 25, waste: 0.1, suppliers: [{ id: 'plast', name: { ar: 'اسمنت اليمامة', en: 'Yamama Cement', fr: 'Ciment Yamama', zh: 'Yamama 水泥' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-PlEx", soilFactor: false, dependency: 'build_area' },

    // ================= 08. أعمال السباكة (Plumbing) =================
    { id: "08.01", category: "mep_plumb", type: "all", name: { ar: "تأسيس تغذية مياه (PPR)", en: "Water Supply Pipes", fr: "Tuyaux Eau", zh: "供水管" }, unit: "نقطة", qty: 40, baseMaterial: 150, baseLabor: 100, waste: 0.05, suppliers: suppliersPlumb, sbc: "SBC 701-Sup", soilFactor: false, dependency: 'rooms_area' },
    { id: "08.02", category: "mep_plumb", type: "all", name: { ar: "تأسيس صرف صحي (مواسير ضغط)", en: "Drainage Pipes", fr: "Tuyaux Drainage", zh: "排水管" }, unit: "نقطة", qty: 40, baseMaterial: 120, baseLabor: 100, waste: 0.05, suppliers: suppliersPlumb, sbc: "SBC 701-Drn", soilFactor: false, dependency: 'rooms_area' },
    { id: "08.03", category: "mep_plumb", type: "all", name: { ar: "خزان مياه علوي (فيبرجلاس)", en: "Roof Water Tank", fr: "Réservoir Toit", zh: "屋顶水箱" }, unit: "عدد", qty: 1, baseMaterial: 2000, baseLabor: 500, waste: 0, suppliers: [{ id: 'tank', name: { ar: 'المهيدب', en: 'Al-Muhaidib', fr: 'Al-Muhaidib', zh: 'Al-Muhaidib' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 701-Tnk", soilFactor: false, dependency: 'fixed' },
    { id: "08.04", category: "mep_plumb", type: "all", name: { ar: "مضخة مياه رفع رئيسية", en: "Submersible/Lift Pump", fr: "Pompe Relevage", zh: "提升泵" }, unit: "عدد", qty: 1, baseMaterial: 1200, baseLabor: 200, waste: 0, suppliers: suppliersPlumb, sbc: "SBC 701-Pmp", soilFactor: false, dependency: 'fixed' },
    { id: "08.05", category: "mep_plumb", type: "all", name: { ar: "مضخة ضغط علوية", en: "Booster Pump", fr: "Surpresseur", zh: "增压泵" }, unit: "عدد", qty: 1, baseMaterial: 1500, baseLabor: 250, waste: 0, suppliers: suppliersPlumb, sbc: "SBC 701-Bst", soilFactor: false, dependency: 'fixed' },
    { id: "08.06", category: "mep_plumb", type: "all", name: { ar: "سخانات مياه (تركيب)", en: "Water Heaters", fr: "Chauffe-eau", zh: "热水器" }, unit: "عدد", qty: 5, baseMaterial: 450, baseLabor: 100, waste: 0, suppliers: [{ id: 'heat', name: { ar: 'الخزف', en: 'Ceramics Co', fr: 'Ceramics Co', zh: '陶瓷公司' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 701-Htr", soilFactor: false, dependency: 'fixed' },
    { id: "08.07", category: "mep_plumb", type: "all", name: { ar: "تركيب أطقم صحيات وخلاطات", en: "Sanitary Ware Sets", fr: "Ensembles Sanitaires", zh: "卫浴套装" }, unit: "طقم", qty: 5, baseMaterial: 1500, baseLabor: 300, waste: 0, suppliers: suppliersFinish, sbc: "SBC 701-Set", soilFactor: false, dependency: 'fixed' },
    { id: "08.08", category: "mep_plumb", type: "all", name: { ar: "غرف تفتيش خارجية (Manholes)", en: "Manholes", fr: "Regards", zh: "人孔" }, unit: "عدد", qty: 6, baseMaterial: 400, baseLabor: 200, waste: 0, suppliers: suppliersConcrete, sbc: "SBC 701-Man", soilFactor: false, dependency: 'fixed' },

    // ================= 09. أعمال الكهرباء (Electrical) =================
    { id: "09.01", category: "mep_elec", type: "all", name: { ar: "نظام تأريض (Grounding)", en: "Grounding System", fr: "Mise à la Terre", zh: "接地系统" }, unit: "مجموعة", qty: 1, baseMaterial: 2500, baseLabor: 1000, waste: 0, suppliers: suppliersElec, sbc: "SBC 401-Grd", soilFactor: false, dependency: 'fixed' },
    { id: "09.02", category: "mep_elec", type: "all", name: { ar: "لوحات توزيع طبالين (MDB/DB)", en: "Dist. Boards (MDB/DB)", fr: "Tableaux Distribution", zh: "配电板" }, unit: "مجموعة", qty: 1, baseMaterial: 5000, baseLabor: 1500, waste: 0, suppliers: suppliersElec, sbc: "SBC 401-DB", soilFactor: false, dependency: 'fixed' },
    { id: "09.03", category: "mep_elec", type: "all", name: { ar: "كابلات رئيسية", en: "Main Cables", fr: "Câbles Principaux", zh: "主电缆" }, unit: "م.ط", qty: 50, baseMaterial: 150, baseLabor: 50, waste: 0.05, suppliers: suppliersElec, sbc: "SBC 401-Cab", soilFactor: false, dependency: 'fixed' },
    { id: "09.04", category: "mep_elec", type: "all", name: { ar: "تأسيس مواسير وعلب", en: "Conduit & Boxes", fr: "Conduits et Boîtes", zh: "导管和盒子" }, unit: "نقطة", qty: 150, baseMaterial: 15, baseLabor: 20, waste: 0.1, suppliers: suppliersElec, sbc: "SBC 401-Cnd", soilFactor: false, dependency: 'sockets_count' },
    { id: "09.05", category: "mep_elec", type: "all", name: { ar: "سحب أسلاك (Wiring)", en: "Wiring", fr: "Câblage", zh: "布线" }, unit: "لفة", qty: 40, baseMaterial: 180, baseLabor: 100, waste: 0.05, suppliers: suppliersElec, sbc: "SBC 401-Wir", soilFactor: false, dependency: 'wire_length' },
    { id: "09.06", category: "mep_elec", type: "all", name: { ar: "تركيب أفياش ومفاتيح", en: "Sockets & Switches Inst.", fr: "Inst. Prises et Interrupteurs", zh: "插座和开关安装" }, unit: "عدد", qty: 150, baseMaterial: 25, baseLabor: 10, waste: 0, suppliers: suppliersSwitches, sbc: "SBC 401-Acc", soilFactor: false, dependency: 'sockets_count' },
    { id: "09.07", category: "mep_elec", type: "all", name: { ar: "ليد وإنارة (Spotlights)", en: "Lighting Fixtures", fr: "Luminaires", zh: "照明设备" }, unit: "عدد", qty: 100, baseMaterial: 35, baseLabor: 15, waste: 0.02, suppliers: suppliersElec, sbc: "SBC 401-Lit", soilFactor: false, dependency: 'build_area' },
    { id: "09.08", category: "mep_elec", type: "all", name: { ar: "نقاط تيار خفيف (داتا/ستالايت)", en: "Low Current Points", fr: "Courant Faible", zh: "弱电点" }, unit: "نقطة", qty: 20, baseMaterial: 40, baseLabor: 25, waste: 0, suppliers: suppliersElec, sbc: "SBC 401-Low", soilFactor: false, dependency: 'fixed' },

    // ================= 10. أعمال التكييف (HVAC) =================
    { id: "10.01", category: "mep_hvac", type: "all", name: { ar: "تأسيس تكييف سبليت (نحاس)", en: "Split AC Piping", fr: "Tuyauterie AC Split", zh: "分体空调管道" }, unit: "م.ط", qty: 120, baseMaterial: 90, baseLabor: 40, waste: 0.05, suppliers: [{ id: 'hvac_pip', name: { ar: 'مولر', en: 'Mueller', fr: 'Mueller', zh: 'Mueller' }, tier: 'premium', priceMultiplier: 1.2 }], sbc: "SBC 501-Pip", soilFactor: false, dependency: 'build_area' },
    { id: "10.02", category: "mep_hvac", type: "all", name: { ar: "تركيب وحدات تكييف", en: "AC Units Installation", fr: "Inst. Unités AC", zh: "空调安装" }, unit: "عدد", qty: 12, baseMaterial: 0, baseLabor: 300, waste: 0, suppliers: [{ id: 'hvac_tech', name: { ar: 'فني تكييف', en: 'AC Tech', fr: 'Tech AC', zh: '空调技师' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 501-Inst", soilFactor: false, dependency: 'fixed' },
    { id: "10.03", category: "mep_hvac", type: "all", name: { ar: "مراوح شفط جدارية وسقفية", en: "Exhaust Fans", fr: "Ventilateurs d\\'Extraction", zh: "排气扇" }, unit: "عدد", qty: 6, baseMaterial: 150, baseLabor: 50, waste: 0, suppliers: [{ id: 'fan_kdk', name: { ar: 'KDK', en: 'KDK', fr: 'KDK', zh: 'KDK' }, tier: 'premium', priceMultiplier: 1.1 }], sbc: "SBC 501-Exh", soilFactor: false, dependency: 'fixed' },

    // ================= 11. التشطيبات الداخلية (Interior Finishes) =================
    { id: "11.01", category: "architecture", type: "all", name: { ar: "أسقف مستعارة (جبس بورد)", en: "False Ceiling (Gypsum)", fr: "Faux Plafond", zh: "石膏吊顶" }, unit: "م2", qty: 450, baseMaterial: 45, baseLabor: 35, waste: 0.1, suppliers: [{ id: 'gyp', name: { ar: 'جبس الأهلية', en: 'National Gypsum', fr: 'Gypse National', zh: '国家石膏' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-Ceil", soilFactor: false, dependency: 'build_area' },
    { id: "11.02", category: "architecture", type: "all", name: { ar: "دهانات داخلية (جوتن/الجزيرة)", en: "Internal Paint", fr: "Peinture Intérieure", zh: "内墙涂料" }, unit: "م2", qty: 1500, baseMaterial: 18, baseLabor: 12, waste: 0.05, suppliers: [{ id: 'jotun', name: { ar: 'جوتن', en: 'Jotun', fr: 'Jotun', zh: '佐敦' }, tier: 'premium', priceMultiplier: 1.2 }], sbc: "SBC 201-Pnt", soilFactor: false, dependency: 'rooms_area' },
    { id: "11.03", category: "architecture", type: "all", name: { ar: "بورسلان أرضيات (استقبال/مجالس)", en: "Porcelain Flooring", fr: "Sol Porcelaine", zh: "瓷砖地板" }, unit: "م2", qty: 150, baseMaterial: 85, baseLabor: 40, waste: 0.08, suppliers: suppliersFinish, sbc: "SBC 201-Flr", soilFactor: false, dependency: 'rooms_area' },
    { id: "11.04", category: "architecture", type: "all", name: { ar: "سيراميك أرضيات (غرف/خدمات)", en: "Ceramic Flooring", fr: "Sol Céramique", zh: "陶瓷地板" }, unit: "م2", qty: 250, baseMaterial: 45, baseLabor: 35, waste: 0.08, suppliers: suppliersFinish, sbc: "SBC 201-Cer", soilFactor: false, dependency: 'rooms_area' },
    { id: "11.05", category: "architecture", type: "all", name: { ar: "سيراميك جدران (حمامات/مطابخ)", en: "Wall Ceramic (Wet Areas)", fr: "Mur Céramique", zh: "墙面陶瓷" }, unit: "م2", qty: 300, baseMaterial: 50, baseLabor: 40, waste: 0.1, suppliers: suppliersFinish, sbc: "SBC 201-WC", soilFactor: false, dependency: 'rooms_area' },
    { id: "11.06", category: "architecture", type: "all", name: { ar: "نعلات بورسلان (Skirting)", en: "Skirting", fr: "Plinthes", zh: "踢脚线" }, unit: "م.ط", qty: 300, baseMaterial: 15, baseLabor: 10, waste: 0.05, suppliers: suppliersFinish, sbc: "SBC 201-Sk", soilFactor: false, dependency: 'build_area' },
    { id: "11.07", category: "architecture", type: "all", name: { ar: "درج رخام (توريد وتركيب)", en: "Marble Staircase", fr: "Escalier Marbre", zh: "大理石楼梯" }, unit: "م.ط", qty: 50, baseMaterial: 250, baseLabor: 100, waste: 0.05, suppliers: suppliersFinish, sbc: "SBC 201-Str", soilFactor: false, dependency: 'fixed' },

    // ================= 12. الأبواب والنوافذ (Doors & Windows) =================
    { id: "12.01", category: "architecture", type: "all", name: { ar: "أبواب خشبية داخلية (WPC)", en: "Internal Wooden Doors", fr: "Portes Bois Int.", zh: "内木门" }, unit: "عدد", qty: 15, baseMaterial: 850, baseLabor: 200, waste: 0, suppliers: [{ id: 'door_wpc', name: { ar: 'مصنع الأبواب', en: 'Door Factory', fr: 'Usine Portes', zh: '门厂' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-Dr", soilFactor: false, dependency: 'build_area' },
    { id: "12.02", category: "architecture", type: "all", name: { ar: "أبواب حديد ومداخل", en: "Steel Doors", fr: "Portes Acier", zh: "钢门" }, unit: "عدد", qty: 4, baseMaterial: 1500, baseLabor: 300, waste: 0, suppliers: [{ id: 'door_stl', name: { ar: 'ورشة حدادة', en: 'Steel Workshop', fr: 'Atelier Acier', zh: '钢铁车间' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-Stl", soilFactor: false, dependency: 'fixed' },
    { id: "12.03", category: "architecture", type: "all", name: { ar: "نوافذ ألمنيوم دبل جلاس", en: "Aluminum Windows", fr: "Fenêtres Alu", zh: "铝窗" }, unit: "م2", qty: 60, baseMaterial: 550, baseLabor: 100, waste: 0, suppliers: suppliersFacades, sbc: "SBC 201-Win", soilFactor: false, dependency: 'build_area' },
    { id: "12.04", category: "architecture", type: "all", name: { ar: "درابزين سلم", en: "Handrails", fr: "Rampes", zh: "扶手" }, unit: "م.ط", qty: 30, baseMaterial: 300, baseLabor: 100, waste: 0, suppliers: [{ id: 'rail', name: { ar: 'أعمال معدنية', en: 'Metal Works', fr: 'Travaux Métal', zh: '金属工程' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 201-Rl", soilFactor: false, dependency: 'fixed' },

    // ================= 13. أعمال الواجهات (Facades) =================
    { id: "13.01", category: "architecture", type: "all", name: { ar: "دهانات واجهات بروفايل", en: "External Paint", fr: "Peinture Extérieure", zh: "外墙涂料" }, unit: "م2", qty: 400, baseMaterial: 22, baseLabor: 15, waste: 0.08, suppliers: [{ id: 'jotun', name: { ar: 'جوتن', en: 'Jotun', fr: 'Jotun', zh: '佐敦' }, tier: 'premium', priceMultiplier: 1.2 }], sbc: "SBC 201-PntEx", soilFactor: false, dependency: 'build_area' },
    { id: "13.02", category: "architecture", type: "all", name: { ar: "تكسيات حجر أو رخام", en: "Natural Stone Cladding", fr: "Revêtement Pierre", zh: "天然石材" }, unit: "م2", qty: 80, baseMaterial: 280, baseLabor: 120, waste: 0.08, suppliers: suppliersFacades, sbc: "SBC 201-Stn", soilFactor: false, dependency: 'facade_stone' },
    { id: "13.03", category: "architecture", type: "all", name: { ar: "كلادينج ألمنيوم", en: "Aluminum Cladding", fr: "Bardage Aluminium", zh: "铝塑板" }, unit: "م2", qty: 0, baseMaterial: 320, baseLabor: 100, waste: 0.05, suppliers: suppliersFacades, sbc: "SBC 201-Cld", soilFactor: false, dependency: 'facade_cladding' },
    { id: "13.04", category: "architecture", type: "all", name: { ar: "واجهات زجاجية (ستركشر)", en: "Glass Facades", fr: "Façades Vitrées", zh: "玻璃幕墙" }, unit: "م2", qty: 0, baseMaterial: 650, baseLabor: 180, waste: 0.03, suppliers: suppliersFacades, sbc: "SBC 201-Gls", soilFactor: false, dependency: 'facade_glass' },
    { id: "13.05", category: "architecture", type: "all", name: { ar: "عناصر تأكيدية جي آر سي", en: "GRC Elements", fr: "Éléments GRC", zh: "GRC构件" }, unit: "م2", qty: 0, baseMaterial: 380, baseLabor: 150, waste: 0.05, suppliers: suppliersFacades, sbc: "SBC 201-GRC", soilFactor: false, dependency: 'build_area' },

    // ================= 14. الأعمال الخارجية (External Works) =================
    { id: "14.01", category: "external_works", type: "all", name: { ar: "بناء سور خارجي", en: "Boundary Wall", fr: "Mur d\\'Enceinte", zh: "围墙" }, unit: "م.ط", qty: 60, baseMaterial: 300, baseLabor: 150, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 304-Wall", soilFactor: false, dependency: 'land_area' },
    { id: "14.02", category: "external_works", type: "all", name: { ar: "بوابة خارجية رئيسية", en: "Main Gate", fr: "Portail Principal", zh: "大门" }, unit: "عدد", qty: 1, baseMaterial: 3000, baseLabor: 800, waste: 0, suppliers: suppliersFacades, sbc: "SBC 201-Gate", soilFactor: false, dependency: 'fixed' },
    { id: "14.03", category: "external_works", type: "all", name: { ar: "بلاط أحواش متداخل (انترلوك)", en: "Interlock Paving", fr: "Pavé Autobloquant", zh: "连锁铺路" }, unit: "م2", qty: 100, baseMaterial: 40, baseLabor: 25, waste: 0.05, suppliers: suppliersConcrete, sbc: "SBC 201-Pav", soilFactor: false, dependency: 'land_area' },
    { id: "14.04", category: "external_works", type: "all", name: { ar: "تنسيق حدائق (زراعة)", en: "Landscaping", fr: "Aménagement Paysager", zh: "景观美化" }, unit: "مقطوعية", qty: 1, baseMaterial: 6000, baseLabor: 4000, waste: 0, suppliers: [{ id: 'land_1', name: { ar: 'شركة تنسيق', en: 'Landscaping Co', fr: 'Paysagiste', zh: '景观公司' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC-Land", soilFactor: false, dependency: 'fixed' },
    { id: "14.05", category: "external_works", type: "all", name: { ar: "إنارة ليلية خارجية", en: "External Lighting", fr: "Éclairage Extérieur", zh: "室外照明" }, unit: "عدد", qty: 8, baseMaterial: 800, baseLabor: 200, waste: 0, suppliers: suppliersElec, sbc: "SBC 401-Ext", soilFactor: false, dependency: 'land_area' },
    { id: "14.06", category: "external_works", type: "all", name: { ar: "بيارة (خزان الصرف الصحى)", en: "Septic Tank", fr: "Fosse Septique", zh: "化粪池" }, unit: "عدد", qty: 1, baseMaterial: 4500, baseLabor: 1500, waste: 0, suppliers: suppliersConcrete, sbc: "SBC 701-Sep", soilFactor: false, dependency: 'fixed' },
    { id: "14.07", category: "external_works", type: "all", name: { ar: "مظلات كراج سيارات", en: "Car Parking Shade", fr: "Abri Voiture", zh: "停车棚" }, unit: "م2", qty: 30, baseMaterial: 180, baseLabor: 80, waste: 0.05, suppliers: suppliersFacades, sbc: "SBC-Shade", soilFactor: false, dependency: 'fixed' },

    // ================= 15. السلامة والحماية (Safety & Protection) =================
    { id: "15.01", category: "safety", type: "all", name: { ar: "نظام إنذار ومكافحة الحريق", en: "Fire System", fr: "Système Incendie", zh: "火灾报警系统" }, unit: "مجموعة", qty: 1, baseMaterial: 8000, baseLabor: 3000, waste: 0, suppliers: [{ id: 'fire_1', name: { ar: 'أنظمة الحماية', en: 'Protection Sys', fr: 'Syst Protection', zh: '保护系统' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 901", soilFactor: false, dependency: 'build_area' },
    { id: "15.02", category: "safety", type: "all", name: { ar: "كواشف دخان", en: "Smoke Detectors", fr: "Détecteurs de Fumée", zh: "烟雾探测器" }, unit: "عدد", qty: 15, baseMaterial: 120, baseLabor: 40, waste: 0, suppliers: [{ id: 'fire_1', name: { ar: 'أنظمة الحماية', en: 'Protection Sys', fr: 'Syst Protection', zh: '保护系统' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 901-Smk", soilFactor: false, dependency: 'build_area' },
    { id: "15.03", category: "safety", type: "all", name: { ar: "طفايات حريق", en: "Fire Extinguishers", fr: "Extincteurs", zh: "灭火器" }, unit: "عدد", qty: 6, baseMaterial: 250, baseLabor: 30, waste: 0, suppliers: [{ id: 'fire_2', name: { ar: 'معدات سلامة', en: 'Safety Equip', fr: 'Équip Sécurité', zh: '安全设备' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 901-Ext", soilFactor: false, dependency: 'fixed' },
    { id: "15.04", category: "safety", type: "all", name: { ar: "صناديق وخراطيم حريق", en: "Fire Hose Reels", fr: "Dévidoirs", zh: "消防水带" }, unit: "عدد", qty: 3, baseMaterial: 1200, baseLabor: 300, waste: 0, suppliers: [{ id: 'fire_1', name: { ar: 'أنظمة الحماية', en: 'Protection Sys', fr: 'Syst Protection', zh: '保护系统' }, tier: 'standard', priceMultiplier: 1 }], sbc: "SBC 901-Hose", soilFactor: false, dependency: 'build_area' },

    // ================= 16. الأيدي العاملة (Manpower) =================
    { id: "16.01", category: "manpower", type: "all", name: { ar: "مهندس موقع", en: "Site Engineer", fr: "Ingénieur de Site", zh: "现场工程师" }, unit: "شهر", qty: 12, baseMaterial: 0, baseLabor: 6000, waste: 0, suppliers: suppliersManpower, sbc: "HR-Eng", soilFactor: false, dependency: 'duration_months', excludeProfit: true },
    { id: "16.02", category: "manpower", type: "all", name: { ar: "مراقب أعمال", en: "Works Supervisor", fr: "Superviseur", zh: "工程监督" }, unit: "شهر", qty: 12, baseMaterial: 0, baseLabor: 4000, waste: 0, suppliers: suppliersManpower, sbc: "HR-Sup", soilFactor: false, dependency: 'duration_months', excludeProfit: true },
    { id: "16.03", category: "manpower", type: "all", name: { ar: "حارس موقع", en: "Site Guard", fr: "Gardien", zh: "保安" }, unit: "شهر", qty: 12, baseMaterial: 0, baseLabor: 1500, waste: 0, suppliers: suppliersManpower, sbc: "HR-Grd", soilFactor: false, dependency: 'duration_months', excludeProfit: true },

    // ================= 17. تجهيزات ومعدات (Equipment & Fixtures) =================
    { id: "17.01", category: "furniture", type: "villa", name: { ar: "خزائن مطبخ", en: "Kitchen Cabinets", fr: "Meubles de Cuisine", zh: "厨房橱柜" }, unit: "م.ط", qty: 8, baseMaterial: 800, baseLabor: 200, waste: 0, suppliers: suppliersFinish, sbc: "SBC-Kit", soilFactor: false, dependency: 'fixed' },
    { id: "17.02", category: "furniture", type: "villa", name: { ar: "خزائن ملابس مدمجة", en: "Built-in Wardrobes", fr: "Placards Intégrés", zh: "内置衣柜" }, unit: "م.ط", qty: 10, baseMaterial: 600, baseLabor: 150, waste: 0, suppliers: suppliersFinish, sbc: "SBC-Ward", soilFactor: false, dependency: 'fixed' },
    { id: "17.03", category: "elevator", type: "all", name: { ar: "مصعد كهربائي", en: "Elevator", fr: "Ascenseur", zh: "电梯" }, unit: "عدد", qty: 0, baseMaterial: 80000, baseLabor: 15000, waste: 0, suppliers: [{ id: 'elev_1', name: { ar: 'أوتيس', en: 'Otis', fr: 'Otis', zh: '奥的斯' }, tier: 'premium', priceMultiplier: 1.2 }], sbc: "SBC-Elev", soilFactor: false, dependency: 'fixed' },
];`;

content = content.replace(/export const ITEMS_DATABASE: BaseItem\[\] = \[\s*[\s\S]*?\n\];/, newDb);

fs.writeFileSync(path, content, 'utf8');
console.log('Successfully replaced ITEMS_DATABASE');
