/**
 * بنود خاصة بالأبراج والمراكز التجارية
 * Tower / Commercial Center Specific Construction Items
 */

import { BaseItem } from '../types';
import {
    SUPPLIERS_CONCRETE, SUPPLIERS_STEEL, SUPPLIERS_TILES,
    SUPPLIERS_SANITARY, SUPPLIERS_HVAC, SUPPLIERS_FACADES,
    SUPPLIERS_ELECTRICAL, SUPPLIERS_ELEVATORS, SUPPLIERS_FIRE_SAFETY,
    SUPPLIERS_PLUMBING, SUPPLIERS_INSULATION, SUPPLIERS_SMART_SECURITY,
    SUPPLIERS_PAINT, SUPPLIERS_DOORS
} from './suppliers';

export const TOWER_ITEMS: BaseItem[] = [
    // ================= T01. الهيكل الإنشائي المتقدم =================
    { id: "T01.01", category: "structure", type: "tower", name: { ar: "خرسانة عالية المقاومة C50/C60", en: "High-Strength Concrete C50/C60", fr: "Béton Haute Résistance C50/C60", zh: "高强度混凝土 C50/C60" }, unit: "م3", qty: 500, baseMaterial: 380, baseLabor: 180, waste: 0.03, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-HS", soilFactor: false, dependency: 'build_area' },
    { id: "T01.02", category: "structure", type: "tower", name: { ar: "خوازيق خرسانية (أساسات عميقة)", en: "Concrete Piling (Deep Foundation)", fr: "Pieux Béton (Fondations Profondes)", zh: "混凝土桩基(深基础)" }, unit: "م.ط", qty: 300, baseMaterial: 450, baseLabor: 200, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Pile", soilFactor: true, dependency: 'build_area' },
    { id: "T01.03", category: "structure", type: "tower", name: { ar: "قبعات خوازيق (Pile Caps)", en: "Pile Caps", fr: "Semelles sur Pieux", zh: "桩帽" }, unit: "م3", qty: 80, baseMaterial: 300, baseLabor: 150, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-PCap", soilFactor: false, dependency: 'build_area' },
    { id: "T01.04", category: "structure", type: "tower", name: { ar: "حديد تسليح كثافة عالية (أبراج)", en: "High-Density Reinforcement Steel (Towers)", fr: "Acier Haute Densité", zh: "高密度钢筋(塔楼)" }, unit: "طن", qty: 200, baseMaterial: 2850, baseLabor: 500, waste: 0.03, suppliers: SUPPLIERS_STEEL, sbc: "SBC 304-HDS", soilFactor: false, dependency: 'build_area' },
    { id: "T01.05", category: "structure", type: "tower", name: { ar: "جدران قص خرسانية (نواة المصاعد)", en: "Shear Walls (Elevator Core)", fr: "Voiles de Contreventement", zh: "剪力墙(电梯核心筒)" }, unit: "م3", qty: 150, baseMaterial: 320, baseLabor: 180, waste: 0.03, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Shear", soilFactor: false, dependency: 'build_area' },
    { id: "T01.06", category: "structure", type: "tower", name: { ar: "بلاطة Flat Slab (بدون كمرات)", en: "Flat Slab (Beam-less)", fr: "Dalle Plate (Sans Poutres)", zh: "无梁楼板" }, unit: "م3", qty: 400, baseMaterial: 290, baseLabor: 140, waste: 0.03, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Flat", soilFactor: false, dependency: 'build_area' },
    { id: "T01.07", category: "structure", type: "tower", name: { ar: "بلاطة Post-Tension (كوابل شد لاحق)", en: "Post-Tensioned Slab", fr: "Dalle Post-Contrainte", zh: "后张预应力楼板" }, unit: "م2", qty: 500, baseMaterial: 180, baseLabor: 90, waste: 0.03, suppliers: SUPPLIERS_STEEL, sbc: "SBC 304-PT", soilFactor: false, dependency: 'build_area' },

    // ================= T02. المصاعد والسلالم المتحركة =================
    { id: "T02.01", category: "mep_elec", type: "tower", name: { ar: "مصاعد ركاب عالية السرعة (2 مصعد)", en: "High-Speed Passenger Elevators (x2)", fr: "Ascenseurs Grande Vitesse (x2)", zh: "高速客梯(2部)" }, unit: "عدد", qty: 2, baseMaterial: 180000, baseLabor: 30000, waste: 0, suppliers: SUPPLIERS_ELEVATORS, sbc: "SBC-Elev", soilFactor: false, dependency: 'fixed' },
    { id: "T02.02", category: "mep_elec", type: "tower", name: { ar: "مصعد خدمة/بضائع (1 مصعد)", en: "Service/Freight Elevator (x1)", fr: "Monte-Charge (x1)", zh: "货梯(1部)" }, unit: "عدد", qty: 1, baseMaterial: 120000, baseLabor: 20000, waste: 0, suppliers: SUPPLIERS_ELEVATORS, sbc: "SBC-Elev-Frgt", soilFactor: false, dependency: 'fixed' },
    { id: "T02.03", category: "mep_elec", type: "tower", name: { ar: "سلالم كهربائية متحركة (Escalators)", en: "Escalators", fr: "Escaliers Mécaniques", zh: "自动扶梯" }, unit: "عدد", qty: 2, baseMaterial: 150000, baseLabor: 25000, waste: 0, suppliers: SUPPLIERS_ELEVATORS, sbc: "SBC-Escl", soilFactor: false, dependency: 'fixed' },

    // ================= T03. المواقف =================
    { id: "T03.01", category: "structure", type: "tower", name: { ar: "مواقف سيارات سرداب (هيكل خرسانة)", en: "Basement Parking Structure", fr: "Parking Souterrain", zh: "地下停车场结构" }, unit: "م2", qty: 800, baseMaterial: 420, baseLabor: 200, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Bsmt", soilFactor: true, dependency: 'build_area' },
    { id: "T03.02", category: "architecture", type: "tower", name: { ar: "أرضيات إيبوكسي (مواقف)", en: "Epoxy Flooring (Parking)", fr: "Sol Époxy (Parking)", zh: "环氧地面(停车场)" }, unit: "م2", qty: 800, baseMaterial: 45, baseLabor: 25, waste: 0.05, suppliers: SUPPLIERS_PAINT, sbc: "SBC 201-Epx", soilFactor: false, dependency: 'build_area' },
    { id: "T03.03", category: "mep_elec", type: "tower", name: { ar: "نظام إدارة المواقف (بوابات + حساسات)", en: "Parking Management System (Gates + Sensors)", fr: "Système Gestion Parking", zh: "停车管理系统(闸机+传感器)" }, unit: "مجموعة", qty: 1, baseMaterial: 35000, baseLabor: 8000, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-Park", soilFactor: false, dependency: 'fixed' },
    { id: "T03.04", category: "mep_plumb", type: "tower", name: { ar: "نظام ضخ وتصريف مياه السرداب", en: "Basement Sump Pump & Drainage", fr: "Pompe de Puisard Sous-Sol", zh: "地下室排水泵系统" }, unit: "مجموعة", qty: 1, baseMaterial: 8000, baseLabor: 3000, waste: 0, suppliers: SUPPLIERS_PLUMBING, sbc: "SBC 701-Sump", soilFactor: false, dependency: 'fixed' },

    // ================= T04. أنظمة HVAC المركزية =================
    { id: "T04.01", category: "mep_hvac", type: "tower", name: { ar: "وحدة تبريد مركزية (Chiller 200TR)", en: "Central Chiller (200TR)", fr: "Groupe Frigorifique Central (200TR)", zh: "中央冷水机组(200冷吨)" }, unit: "عدد", qty: 1, baseMaterial: 350000, baseLabor: 50000, waste: 0, suppliers: SUPPLIERS_HVAC, sbc: "SBC 501-Chll", soilFactor: false, dependency: 'fixed' },
    { id: "T04.02", category: "mep_hvac", type: "tower", name: { ar: "مجاري هواء (Ductwork) معزولة", en: "Insulated Ductwork", fr: "Gaines Isolées", zh: "保温风管" }, unit: "م2", qty: 2000, baseMaterial: 80, baseLabor: 50, waste: 0.1, suppliers: SUPPLIERS_HVAC, sbc: "SBC 501-Duct", soilFactor: false, dependency: 'build_area' },
    { id: "T04.03", category: "mep_hvac", type: "tower", name: { ar: "وحدات تداول الهواء (AHU)", en: "Air Handling Units (AHU)", fr: "Centrales de Traitement d'Air", zh: "空气处理机组(AHU)" }, unit: "عدد", qty: 4, baseMaterial: 25000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_HVAC, sbc: "SBC 501-AHU", soilFactor: false, dependency: 'fixed' },
    { id: "T04.04", category: "mep_hvac", type: "tower", name: { ar: "نظام BMS (إدارة المبنى الذكية)", en: "Building Management System (BMS)", fr: "Système de Gestion du Bâtiment", zh: "楼宇管理系统(BMS)" }, unit: "مجموعة", qty: 1, baseMaterial: 80000, baseLabor: 20000, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 501-BMS", soilFactor: false, dependency: 'fixed' },
    { id: "T04.05", category: "mep_hvac", type: "tower", name: { ar: "نظام شفط وتهوية المواقف", en: "Parking Ventilation & Exhaust System", fr: "Ventilation Parking", zh: "停车场通风排烟系统" }, unit: "مجموعة", qty: 1, baseMaterial: 40000, baseLabor: 12000, waste: 0, suppliers: SUPPLIERS_HVAC, sbc: "SBC 501-PrkVn", soilFactor: false, dependency: 'fixed' },

    // ================= T05. أنظمة الحريق المتقدمة =================
    { id: "T05.01", category: "safety", type: "tower", name: { ar: "نظام رش مائي (Sprinklers) شامل", en: "Full Sprinkler System", fr: "Système Sprinkler Complet", zh: "全面喷淋系统" }, unit: "رأس", qty: 200, baseMaterial: 350, baseLabor: 120, waste: 0.05, suppliers: SUPPLIERS_FIRE_SAFETY, sbc: "SBC 901-Spk", soilFactor: false, dependency: 'build_area' },
    { id: "T05.02", category: "safety", type: "tower", name: { ar: "مضخات حريق (Jockey + Electric + Diesel)", en: "Fire Pump Set (Jockey+Electric+Diesel)", fr: "Groupe de Pompes Incendie", zh: "消防泵组" }, unit: "مجموعة", qty: 1, baseMaterial: 60000, baseLabor: 15000, waste: 0, suppliers: SUPPLIERS_FIRE_SAFETY, sbc: "SBC 901-Pump", soilFactor: false, dependency: 'fixed' },
    { id: "T05.03", category: "safety", type: "tower", name: { ar: "نظام إطفاء FM200 (غرف الكهرباء)", en: "FM200 Suppression (Electrical Rooms)", fr: "Système FM200", zh: "FM200灭火系统(电气室)" }, unit: "مجموعة", qty: 2, baseMaterial: 25000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_FIRE_SAFETY, sbc: "SBC 901-FM", soilFactor: false, dependency: 'fixed' },
    { id: "T05.04", category: "safety", type: "tower", name: { ar: "مروحة شفط دخان (Smoke Exhaust)", en: "Smoke Exhaust Fans", fr: "Ventilateurs Désenfumage", zh: "排烟风机" }, unit: "عدد", qty: 4, baseMaterial: 8000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_FIRE_SAFETY, sbc: "SBC 901-SmkFn", soilFactor: false, dependency: 'fixed' },
    { id: "T05.05", category: "safety", type: "tower", name: { ar: "أبواب مقاومة للحريق (Fire-Rated)", en: "Fire-Rated Doors", fr: "Portes Coupe-Feu", zh: "防火门" }, unit: "عدد", qty: 20, baseMaterial: 2500, baseLabor: 500, waste: 0, suppliers: SUPPLIERS_DOORS, sbc: "SBC 901-FRDr", soilFactor: false, dependency: 'build_area' },
    { id: "T05.06", category: "safety", type: "tower", name: { ar: "درج طوارئ مضغوط (Pressurized Stairwell)", en: "Pressurized Emergency Stairwell", fr: "Cage d'Escalier Pressurisée", zh: "正压送风楼梯间" }, unit: "مجموعة", qty: 2, baseMaterial: 15000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_FIRE_SAFETY, sbc: "SBC 901-Prss", soilFactor: false, dependency: 'fixed' },

    // ================= T06. الكهرباء المتقدمة =================
    { id: "T06.01", category: "mep_elec", type: "tower", name: { ar: "محولات كهرباء (1000 KVA)", en: "Transformer (1000 KVA)", fr: "Transformateur (1000 KVA)", zh: "变压器(1000KVA)" }, unit: "عدد", qty: 2, baseMaterial: 120000, baseLabor: 15000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-Trf", soilFactor: false, dependency: 'fixed' },
    { id: "T06.02", category: "mep_elec", type: "tower", name: { ar: "لوحة توزيع رئيسية (Main Switchboard)", en: "Main Switchboard", fr: "Tableau Général Basse Tension", zh: "主配电柜" }, unit: "مجموعة", qty: 1, baseMaterial: 45000, baseLabor: 10000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-MSB", soilFactor: false, dependency: 'fixed' },
    { id: "T06.03", category: "mep_elec", type: "tower", name: { ar: "UPS مركزي (احتياطي كهرباء)", en: "Central UPS System", fr: "Système UPS Central", zh: "中央UPS系统" }, unit: "مجموعة", qty: 1, baseMaterial: 30000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-UPS", soilFactor: false, dependency: 'fixed' },
    { id: "T06.04", category: "mep_elec", type: "tower", name: { ar: "مولد ديزل احتياطي (500 كيلو واط)", en: "Emergency Diesel Generator (500kW)", fr: "Groupe Électrogène (500kW)", zh: "应急柴油发电机(500千瓦)" }, unit: "عدد", qty: 1, baseMaterial: 250000, baseLabor: 30000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-DGen", soilFactor: false, dependency: 'fixed' },
    { id: "T06.05", category: "mep_elec", type: "tower", name: { ar: "نظام حماية من الصواعق (Lightning Protection)", en: "Lightning Protection System", fr: "Système Parafoudre", zh: "防雷系统" }, unit: "مجموعة", qty: 1, baseMaterial: 15000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-Lgtn", soilFactor: false, dependency: 'fixed' },

    // ================= T07. الواجهات =================
    { id: "T07.01", category: "architecture", type: "tower", name: { ar: "واجهات زجاجية حرارية (Curtain Wall)", en: "Thermally-Broken Curtain Wall", fr: "Mur-Rideau à Rupture Thermique", zh: "断热铝合金幕墙" }, unit: "م2", qty: 1500, baseMaterial: 800, baseLabor: 250, waste: 0.05, suppliers: SUPPLIERS_FACADES, sbc: "SBC 201-CW", soilFactor: false, dependency: 'build_area' },
    { id: "T07.02", category: "architecture", type: "tower", name: { ar: "كلادينج ألمنيوم مركب (ACM)", en: "Aluminum Composite Cladding (ACM)", fr: "Bardage Composite Aluminium", zh: "铝塑复合板幕墙" }, unit: "م2", qty: 500, baseMaterial: 350, baseLabor: 120, waste: 0.05, suppliers: SUPPLIERS_FACADES, sbc: "SBC 201-ACM", soilFactor: false, dependency: 'build_area' },

    // ================= T08. المساحات المشتركة والتجارية =================
    { id: "T08.01", category: "architecture", type: "tower", name: { ar: "لوبي رئيسي فاخر (رخام + إضاءة)", en: "Premium Main Lobby (Marble + Lighting)", fr: "Hall Principal Luxe", zh: "豪华主大堂(大理石+照明)" }, unit: "م2", qty: 100, baseMaterial: 500, baseLabor: 200, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Lobby", soilFactor: false, dependency: 'fixed' },
    { id: "T08.02", category: "architecture", type: "tower", name: { ar: "معارض/محلات تجارية (تجهيز Shell & Core)", en: "Retail Shops (Shell & Core Fit-out)", fr: "Locaux Commerciaux (Coque)", zh: "商铺(毛坯交付)" }, unit: "م2", qty: 400, baseMaterial: 250, baseLabor: 100, waste: 0.05, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Shop", soilFactor: false, dependency: 'build_area' },
    { id: "T08.03", category: "architecture", type: "tower", name: { ar: "منطقة استقبال وكونتر (Reception)", en: "Reception Area & Counter", fr: "Zone d'Accueil", zh: "接待区和前台" }, unit: "مجموعة", qty: 1, baseMaterial: 12000, baseLabor: 3000, waste: 0, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Rcpt", soilFactor: false, dependency: 'fixed' },
    { id: "T08.04", category: "mep_plumb", type: "tower", name: { ar: "دورات مياه عامة (كل دور)", en: "Public Restrooms (Per Floor)", fr: "Sanitaires Publics (Par Étage)", zh: "公共卫生间(每层)" }, unit: "مجموعة", qty: 10, baseMaterial: 8000, baseLabor: 3000, waste: 0, suppliers: SUPPLIERS_SANITARY, sbc: "SBC 701-PubWC", soilFactor: false, dependency: 'fixed' },
];
