/**
 * بنود خاصة بالفلل السكنية
 * Villa-Specific Construction Items
 * تشمل بنود غير موجودة في البنود العامة (type: 'all')
 */

import { BaseItem } from '../types';
import {
    SUPPLIERS_TILES, SUPPLIERS_SANITARY, SUPPLIERS_KITCHENS,
    SUPPLIERS_HVAC, SUPPLIERS_FACADES, SUPPLIERS_PAINT,
    SUPPLIERS_CONCRETE, SUPPLIERS_STEEL, SUPPLIERS_INSULATION,
    SUPPLIERS_PLUMBING, SUPPLIERS_ELECTRICAL, SUPPLIERS_ELEVATORS,
    SUPPLIERS_LANDSCAPING, SUPPLIERS_FIRE_SAFETY, SUPPLIERS_DOORS,
    SUPPLIERS_SMART_SECURITY, SUPPLIERS_BLOCKS, SUPPLIERS_SOLAR
} from './suppliers';

export const VILLA_ITEMS: BaseItem[] = [
    // ================= V01. أعمال السور والبوابات =================
    { id: "V01.01", category: "architecture", type: "villa", name: { ar: "سور خارجي مع أعمدة حجرية", en: "Boundary Wall with Stone Pillars", fr: "Mur d'Enceinte avec Piliers", zh: "带石柱围墙" }, unit: "م.ط", qty: 80, baseMaterial: 400, baseLabor: 200, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Wall", soilFactor: false, dependency: 'land_area' },
    { id: "V01.02", category: "architecture", type: "villa", name: { ar: "بوابة رئيسية كهربائية (حديد مشغول)", en: "Electric Main Gate (Wrought Iron)", fr: "Portail Électrique (Fer Forgé)", zh: "电动铁艺大门" }, unit: "عدد", qty: 1, baseMaterial: 8000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_FACADES, sbc: "SBC 201-Gate", soilFactor: false, dependency: 'fixed' },
    { id: "V01.03", category: "architecture", type: "villa", name: { ar: "بوابة فرعية (مشاة)", en: "Pedestrian Side Gate", fr: "Portillon Piéton", zh: "行人侧门" }, unit: "عدد", qty: 1, baseMaterial: 2500, baseLabor: 500, waste: 0, suppliers: SUPPLIERS_FACADES, sbc: "SBC 201-Gate2", soilFactor: false, dependency: 'fixed' },
    { id: "V01.04", category: "architecture", type: "villa", name: { ar: "تبليط أعلى السور (Cap Stone)", en: "Wall Cap Stone", fr: "Chaperon de Mur", zh: "墙帽石" }, unit: "م.ط", qty: 80, baseMaterial: 45, baseLabor: 20, waste: 0.05, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Cap", soilFactor: false, dependency: 'land_area' },

    // ================= V02. الملحق الخارجي =================
    { id: "V02.01", category: "structure", type: "villa", name: { ar: "ملحق خارجي (مجلس رجال) — هيكل", en: "External Annex (Men's Majlis) — Structure", fr: "Annexe Extérieure (Majlis) — Structure", zh: "外部附楼(男士客厅)结构" }, unit: "م2", qty: 50, baseMaterial: 350, baseLabor: 180, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Anx", soilFactor: false, dependency: 'fixed' },
    { id: "V02.02", category: "architecture", type: "villa", name: { ar: "تشطيب ملحق خارجي (بورسلان + جبس)", en: "External Annex Finishing", fr: "Finition Annexe Extérieure", zh: "外部附楼装修" }, unit: "م2", qty: 50, baseMaterial: 280, baseLabor: 150, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-AnxFin", soilFactor: false, dependency: 'fixed' },
    { id: "V02.03", category: "mep_hvac", type: "villa", name: { ar: "تكييف ملحق (سبليت)", en: "Annex AC (Split Unit)", fr: "Clim Annexe (Split)", zh: "附楼空调(分体)" }, unit: "عدد", qty: 2, baseMaterial: 2800, baseLabor: 400, waste: 0, suppliers: SUPPLIERS_HVAC, sbc: "SBC 501-Anx", soilFactor: false, dependency: 'fixed' },

    // ================= V03. المسبح والأحواض =================
    { id: "V03.01", category: "structure", type: "villa", name: { ar: "مسبح خرساني (6×3م) — حفر وخرسانة", en: "Concrete Pool (6x3m) — Excavation & Concrete", fr: "Piscine Béton (6x3m)", zh: "混凝土泳池(6x3米)" }, unit: "مجموعة", qty: 1, baseMaterial: 18000, baseLabor: 8000, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Pool", soilFactor: false, dependency: 'fixed' },
    { id: "V03.02", category: "insulation", type: "villa", name: { ar: "عزل مائي للمسبح (إيبوكسي)", en: "Pool Waterproofing (Epoxy)", fr: "Étanchéité Piscine (Époxy)", zh: "泳池防水(环氧)" }, unit: "م2", qty: 50, baseMaterial: 65, baseLabor: 40, waste: 0.1, suppliers: SUPPLIERS_INSULATION, sbc: "SBC 1101-Pool", soilFactor: false, dependency: 'fixed' },
    { id: "V03.03", category: "architecture", type: "villa", name: { ar: "بلاط مسابح (موزاييك زجاجي)", en: "Pool Mosaic Tiles", fr: "Mosaïque Piscine", zh: "泳池马赛克" }, unit: "م2", qty: 50, baseMaterial: 120, baseLabor: 60, waste: 0.1, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Pool", soilFactor: false, dependency: 'fixed' },
    { id: "V03.04", category: "mep_plumb", type: "villa", name: { ar: "نظام فلترة وتدوير مياه المسبح", en: "Pool Filtration & Circulation System", fr: "Système Filtration Piscine", zh: "泳池过滤循环系统" }, unit: "مجموعة", qty: 1, baseMaterial: 6000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_PLUMBING, sbc: "SBC 701-Pool", soilFactor: false, dependency: 'fixed' },
    { id: "V03.05", category: "mep_elec", type: "villa", name: { ar: "إنارة مسبح (LED مقاومة للماء)", en: "Pool LED Lighting (Waterproof)", fr: "Éclairage Piscine LED", zh: "泳池LED灯(防水)" }, unit: "عدد", qty: 4, baseMaterial: 350, baseLabor: 150, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-Pool", soilFactor: false, dependency: 'fixed' },
    { id: "V03.06", category: "mep_plumb", type: "villa", name: { ar: "تدفئة مسبح (سخان حراري)", en: "Pool Heating System", fr: "Chauffage Piscine", zh: "泳池加热系统" }, unit: "مجموعة", qty: 1, baseMaterial: 4500, baseLabor: 1000, waste: 0, suppliers: SUPPLIERS_PLUMBING, sbc: "SBC 701-PoolHt", soilFactor: false, dependency: 'fixed' },

    // ================= V04. تشطيبات فاخرة =================
    { id: "V04.01", category: "architecture", type: "villa", name: { ar: "أرضيات رخام طبيعي (استقبال/مجالس)", en: "Natural Marble Flooring (Reception)", fr: "Sol Marbre Naturel", zh: "天然大理石地面(接待)" }, unit: "م2", qty: 80, baseMaterial: 350, baseLabor: 80, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Mrb", soilFactor: false, dependency: 'rooms_area' },
    { id: "V04.02", category: "architecture", type: "villa", name: { ar: "أرضيات باركيه خشبي (غرف نوم)", en: "Wood Parquet Flooring (Bedrooms)", fr: "Parquet Bois", zh: "实木地板(卧室)" }, unit: "م2", qty: 100, baseMaterial: 180, baseLabor: 50, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Prk", soilFactor: false, dependency: 'rooms_area' },
    { id: "V04.03", category: "architecture", type: "villa", name: { ar: "جبس بورد ديكور (كرانيش وإضاءة مخفية)", en: "Decorative Gypsum Board (Cornices & Cove Light)", fr: "Gypse Décoratif", zh: "装饰石膏板(灯槽)" }, unit: "م.ط", qty: 200, baseMaterial: 65, baseLabor: 45, waste: 0.1, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-GyDc", soilFactor: false, dependency: 'build_area' },
    { id: "V04.04", category: "architecture", type: "villa", name: { ar: "ورق جدران فاخر (غرف نوم رئيسية)", en: "Premium Wallpaper (Master Bedrooms)", fr: "Papier Peint Luxe", zh: "高档壁纸(主卧)" }, unit: "م2", qty: 40, baseMaterial: 95, baseLabor: 35, waste: 0.1, suppliers: SUPPLIERS_PAINT, sbc: "SBC 201-WP", soilFactor: false, dependency: 'rooms_area' },
    { id: "V04.05", category: "architecture", type: "villa", name: { ar: "كسوة خشبية للجدران (لامينات طبيعي)", en: "Wood Wall Paneling", fr: "Lambris Bois", zh: "木质墙板" }, unit: "م²", qty: 30, baseMaterial: 200, baseLabor: 70, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-WdPnl", soilFactor: false, dependency: 'rooms_area' },

    // ================= V05. المطبخ والخزائن =================
    { id: "V05.01", category: "architecture", type: "villa", name: { ar: "مطبخ رئيسي (دولاب ألمنيوم/خشب)", en: "Main Kitchen (Cabinet Setup)", fr: "Cuisine Principale", zh: "主厨房(橱柜)" }, unit: "م.ط", qty: 10, baseMaterial: 1200, baseLabor: 300, waste: 0, suppliers: SUPPLIERS_KITCHENS, sbc: "SBC-Kit", soilFactor: false, dependency: 'fixed' },
    { id: "V05.02", category: "architecture", type: "villa", name: { ar: "مطبخ تحضيري (Pantry)", en: "Prep Kitchen (Pantry)", fr: "Office de Cuisine", zh: "备餐厨房" }, unit: "م.ط", qty: 5, baseMaterial: 900, baseLabor: 200, waste: 0, suppliers: SUPPLIERS_KITCHENS, sbc: "SBC-Kit2", soilFactor: false, dependency: 'fixed' },
    { id: "V05.03", category: "architecture", type: "villa", name: { ar: "خزائن ملابس مدمجة (Walk-in Closet)", en: "Walk-in Closets", fr: "Dressings", zh: "步入式衣柜" }, unit: "م.ط", qty: 15, baseMaterial: 700, baseLabor: 180, waste: 0, suppliers: SUPPLIERS_KITCHENS, sbc: "SBC-Ward", soilFactor: false, dependency: 'fixed' },
    { id: "V05.04", category: "mep_plumb", type: "villa", name: { ar: "أجهزة مطبخ (شفاط + فرن + غسالة أطباق)", en: "Kitchen Appliances (Hood+Oven+Dishwasher)", fr: "Appareils Cuisine", zh: "厨房电器(排油烟机+烤箱+洗碗机)" }, unit: "مجموعة", qty: 1, baseMaterial: 8000, baseLabor: 1000, waste: 0, suppliers: SUPPLIERS_KITCHENS, sbc: "SBC-KitApp", soilFactor: false, dependency: 'fixed' },

    // ================= V06. الحمامات الفاخرة =================
    { id: "V06.01", category: "mep_plumb", type: "villa", name: { ar: "حمام ماستر (جاكوزي + دش ريين + بيديه)", en: "Master Bathroom (Jacuzzi + Rain Shower + Bidet)", fr: "Salle de Bain Master", zh: "主浴室(按摩浴缸+花洒+坐浴)" }, unit: "مجموعة", qty: 1, baseMaterial: 12000, baseLabor: 3000, waste: 0, suppliers: SUPPLIERS_SANITARY, sbc: "SBC 701-Mst", soilFactor: false, dependency: 'fixed' },
    { id: "V06.02", category: "mep_plumb", type: "villa", name: { ar: "حمام ضيوف (رخام كامل)", en: "Guest Bathroom (Full Marble)", fr: "Salle de Bain Invités", zh: "客浴室(全大理石)" }, unit: "مجموعة", qty: 1, baseMaterial: 6000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_SANITARY, sbc: "SBC 701-Gst", soilFactor: false, dependency: 'fixed' },
    { id: "V06.03", category: "architecture", type: "villa", name: { ar: "مرايا حمامات (مضيئة LED)", en: "Bathroom LED Mirrors", fr: "Miroirs LED", zh: "LED浴室镜" }, unit: "عدد", qty: 5, baseMaterial: 600, baseLabor: 100, waste: 0, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Mrr", soilFactor: false, dependency: 'fixed' },

    // ================= V07. الحدائق والتنسيق الخارجي =================
    { id: "V07.01", category: "architecture", type: "villa", name: { ar: "تنسيق حدائق شاملة (عشب + أشجار + إنارة)", en: "Full Landscaping (Grass + Trees + Lights)", fr: "Aménagement Paysager Complet", zh: "全面景观美化" }, unit: "م2", qty: 120, baseMaterial: 80, baseLabor: 50, waste: 0.1, suppliers: SUPPLIERS_LANDSCAPING, sbc: "SBC-Land", soilFactor: false, dependency: 'land_area' },
    { id: "V07.02", category: "architecture", type: "villa", name: { ar: "جلسة خارجية (بيرجولا خشب/حديد)", en: "Outdoor Pergola (Wood/Steel)", fr: "Pergola Extérieure", zh: "室外廊架(木/钢)" }, unit: "م2", qty: 20, baseMaterial: 350, baseLabor: 150, waste: 0.05, suppliers: SUPPLIERS_FACADES, sbc: "SBC-Perg", soilFactor: false, dependency: 'fixed' },
    { id: "V07.03", category: "architecture", type: "villa", name: { ar: "مظلات سيارات حديد/شد (3 سيارات)", en: "Car Parking Shade (3 Cars)", fr: "Abri Voiture (3 Places)", zh: "停车棚(3辆)" }, unit: "م2", qty: 45, baseMaterial: 200, baseLabor: 90, waste: 0.05, suppliers: SUPPLIERS_STEEL, sbc: "SBC-Shade", soilFactor: false, dependency: 'fixed' },
    { id: "V07.04", category: "mep_plumb", type: "villa", name: { ar: "شبكة ري أوتوماتيكية للحديقة", en: "Automatic Garden Irrigation System", fr: "Système d'Irrigation Automatique", zh: "自动花园灌溉系统" }, unit: "مجموعة", qty: 1, baseMaterial: 3500, baseLabor: 1200, waste: 0.05, suppliers: SUPPLIERS_PLUMBING, sbc: "SBC 701-Irr", soilFactor: false, dependency: 'fixed' },
    { id: "V07.05", category: "architecture", type: "villa", name: { ar: "ممرات حجر طبيعي (حديقة)", en: "Natural Stone Pathways", fr: "Allées en Pierre", zh: "天然石材小路" }, unit: "م2", qty: 30, baseMaterial: 120, baseLabor: 60, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-Path", soilFactor: false, dependency: 'land_area' },
    { id: "V07.06", category: "architecture", type: "villa", name: { ar: "شلال مائي ديكوري", en: "Decorative Water Feature/Fountain", fr: "Fontaine Décorative", zh: "装饰瀑布/喷泉" }, unit: "مجموعة", qty: 1, baseMaterial: 5000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_LANDSCAPING, sbc: "SBC-Fount", soilFactor: false, dependency: 'fixed' },
    { id: "V07.07", category: "mep_elec", type: "villa", name: { ar: "إنارة خارجية (حدائق + ممرات + أعمدة)", en: "Garden & Pathway Lighting", fr: "Éclairage Extérieur Jardin", zh: "花园和小路照明" }, unit: "عدد", qty: 15, baseMaterial: 400, baseLabor: 120, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-ExtGrd", soilFactor: false, dependency: 'land_area' },
    { id: "V07.08", category: "architecture", type: "villa", name: { ar: "بيت شعر/خيمة خارجية", en: "Traditional Tent (Beit Sha'r)", fr: "Tente Traditionnelle", zh: "传统帐篷" }, unit: "م2", qty: 25, baseMaterial: 250, baseLabor: 100, waste: 0.05, suppliers: SUPPLIERS_FACADES, sbc: "SBC-Tent", soilFactor: false, dependency: 'fixed' },

    // ================= V08. الأنظمة الذكية والأمنية =================
    { id: "V08.01", category: "mep_elec", type: "villa", name: { ar: "نظام سمارت هوم شامل (إضاءة + ستائر + تكييف)", en: "Full Smart Home System", fr: "Système Maison Intelligente", zh: "全屋智能系统" }, unit: "مجموعة", qty: 1, baseMaterial: 18000, baseLabor: 5000, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-SmHm", soilFactor: false, dependency: 'fixed' },
    { id: "V08.02", category: "mep_elec", type: "villa", name: { ar: "نظام كاميرات مراقبة (8 كاميرات + NVR)", en: "CCTV System (8 Cameras + NVR)", fr: "Système CCTV (8 Caméras)", zh: "监控系统(8摄像头+NVR)" }, unit: "مجموعة", qty: 1, baseMaterial: 5000, baseLabor: 1500, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-CCTV", soilFactor: false, dependency: 'fixed' },
    { id: "V08.03", category: "mep_elec", type: "villa", name: { ar: "نظام إنتركم فيديو (شاشة + كاميرا باب)", en: "Video Intercom System", fr: "Interphone Vidéo", zh: "视频对讲系统" }, unit: "مجموعة", qty: 1, baseMaterial: 3000, baseLabor: 800, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-Int", soilFactor: false, dependency: 'fixed' },
    { id: "V08.04", category: "mep_elec", type: "villa", name: { ar: "نظام إنذار ضد السرقة", en: "Burglar Alarm System", fr: "Système Anti-Intrusion", zh: "防盗报警系统" }, unit: "مجموعة", qty: 1, baseMaterial: 3500, baseLabor: 1000, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-Alrm", soilFactor: false, dependency: 'fixed' },
    { id: "V08.05", category: "mep_elec", type: "villa", name: { ar: "قفل ذكي للأبواب (بصمة + كارت + كود)", en: "Smart Door Locks (Fingerprint + Card + Code)", fr: "Serrures Intelligentes", zh: "智能门锁(指纹+卡+密码)" }, unit: "عدد", qty: 3, baseMaterial: 1200, baseLabor: 200, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-SmLk", soilFactor: false, dependency: 'fixed' },

    // ================= V09. مصعد وسلالم =================
    { id: "V09.01", category: "mep_elec", type: "villa", name: { ar: "مصعد منزلي (شخصين/3 وقفات)", en: "Home Elevator (2 Person / 3 Stops)", fr: "Ascenseur Résidentiel", zh: "家用电梯(2人/3停靠)" }, unit: "عدد", qty: 1, baseMaterial: 75000, baseLabor: 14000, waste: 0, suppliers: SUPPLIERS_ELEVATORS, sbc: "SBC-Elev", soilFactor: false, dependency: 'fixed' }, // v2.0: سعر سوق 2026
    { id: "V09.02", category: "architecture", type: "villa", name: { ar: "تكسية درج رخام طبيعي (كريمة/إمبرادور)", en: "Marble Staircase Cladding", fr: "Revêtement Escalier Marbre", zh: "大理石楼梯贴面" }, unit: "م.ط", qty: 55, baseMaterial: 320, baseLabor: 120, waste: 0.08, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-StrMrb", soilFactor: false, dependency: 'fixed' },
    { id: "V09.03", category: "architecture", type: "villa", name: { ar: "درابزين زجاج + ستانلس ستيل", en: "Glass + Stainless Steel Railing", fr: "Garde-Corps Verre + Inox", zh: "玻璃+不锈钢扶手" }, unit: "م.ط", qty: 25, baseMaterial: 450, baseLabor: 150, waste: 0, suppliers: SUPPLIERS_FACADES, sbc: "SBC 201-RlGls", soilFactor: false, dependency: 'fixed' },

    // ================= V10. غرفة السائق والخدم =================
    { id: "V10.01", category: "structure", type: "villa", name: { ar: "غرفة سائق (هيكل + تشطيب)", en: "Driver's Room (Structure + Finish)", fr: "Chambre Chauffeur", zh: "司机房(结构+装修)" }, unit: "م2", qty: 16, baseMaterial: 500, baseLabor: 250, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Drv", soilFactor: false, dependency: 'fixed' },
    { id: "V10.02", category: "structure", type: "villa", name: { ar: "غرفة خادمة مع حمام (هيكل + تشطيب)", en: "Maid's Room with Bathroom", fr: "Chambre Domestique avec SDB", zh: "女佣房含浴室" }, unit: "م2", qty: 12, baseMaterial: 550, baseLabor: 280, waste: 0.05, suppliers: SUPPLIERS_CONCRETE, sbc: "SBC 304-Maid", soilFactor: false, dependency: 'fixed' },

    // ================= V11. الطاقة الشمسية والمولدات =================
    { id: "V11.01", category: "mep_elec", type: "villa", name: { ar: "نظام طاقة شمسية (10 كيلو واط)", en: "Solar Power System (10kW)", fr: "Système Solaire (10kW)", zh: "太阳能系统(10千瓦)" }, unit: "مجموعة", qty: 1, baseMaterial: 32000, baseLabor: 8000, waste: 0, suppliers: SUPPLIERS_SOLAR, sbc: "SBC 401-Sol", soilFactor: false, dependency: 'fixed' },
    { id: "V11.02", category: "mep_elec", type: "villa", name: { ar: "مولد كهرباء احتياطي (20 كيلو)", en: "Backup Generator (20kW)", fr: "Générateur de Secours (20kW)", zh: "备用发电机(20千瓦)" }, unit: "عدد", qty: 1, baseMaterial: 18000, baseLabor: 3000, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-Gen", soilFactor: false, dependency: 'fixed' },

    // ================= V12. أعمال إضافية =================
    { id: "V12.01", category: "mep_plumb", type: "villa", name: { ar: "غرفة غسيل (توصيلات + أرفف)", en: "Laundry Room (Plumbing + Shelving)", fr: "Buanderie", zh: "洗衣房(管道+架子)" }, unit: "مجموعة", qty: 1, baseMaterial: 3000, baseLabor: 1000, waste: 0, suppliers: SUPPLIERS_PLUMBING, sbc: "SBC 701-Lndr", soilFactor: false, dependency: 'fixed' },
    { id: "V12.02", category: "architecture", type: "villa", name: { ar: "مستودع/مخزن (تحت الدرج)", en: "Storage Room (Under Staircase)", fr: "Rangement (Sous Escalier)", zh: "储物间(楼梯下)" }, unit: "م2", qty: 6, baseMaterial: 150, baseLabor: 80, waste: 0.05, suppliers: SUPPLIERS_DOORS, sbc: "SBC-Stor", soilFactor: false, dependency: 'fixed' },
    { id: "V12.03", category: "mep_elec", type: "villa", name: { ar: "نظام تسخين مياه شمسي", en: "Solar Water Heating System", fr: "Chauffe-eau Solaire", zh: "太阳能热水系统" }, unit: "مجموعة", qty: 1, baseMaterial: 5000, baseLabor: 1500, waste: 0, suppliers: SUPPLIERS_SOLAR, sbc: "SBC 701-SolHt", soilFactor: false, dependency: 'fixed' },
    { id: "V12.04", category: "mep_elec", type: "villa", name: { ar: "ستائر كهربائية (شتر/رول)", en: "Electric Window Shutters/Blinds", fr: "Volets Roulants Électriques", zh: "电动窗帘/卷帘" }, unit: "عدد", qty: 12, baseMaterial: 800, baseLabor: 200, waste: 0, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC-Shtr", soilFactor: false, dependency: 'build_area' },
    { id: "V12.05", category: "mep_elec", type: "villa", name: { ar: "نظام صوت مركزي (Multi-Room Audio)", en: "Multi-Room Audio System", fr: "Système Audio Multi-Pièces", zh: "多房间音响系统" }, unit: "مجموعة", qty: 1, baseMaterial: 6000, baseLabor: 2000, waste: 0, suppliers: SUPPLIERS_SMART_SECURITY, sbc: "SBC 401-Aud", soilFactor: false, dependency: 'fixed' },
    { id: "V12.06", category: "mep_elec", type: "villa", name: { ar: "نظام شبكة بيانات سلكية (CAT6A)", en: "Wired Data Network (CAT6A)", fr: "Réseau Câblé (CAT6A)", zh: "有线数据网络(CAT6A)" }, unit: "نقطة", qty: 20, baseMaterial: 55, baseLabor: 30, waste: 0.05, suppliers: SUPPLIERS_ELECTRICAL, sbc: "SBC 401-Net", soilFactor: false, dependency: 'fixed' },
    { id: "V12.07", category: "architecture", type: "villa", name: { ar: "مدخنة ديكورية (مجلس)", en: "Decorative Fireplace (Majlis)", fr: "Cheminée Décorative", zh: "装饰壁炉(客厅)" }, unit: "عدد", qty: 1, baseMaterial: 4000, baseLabor: 1500, waste: 0, suppliers: SUPPLIERS_TILES, sbc: "SBC 201-FP", soilFactor: false, dependency: 'fixed' },
];
